// ============================================================================
//  PORTFOLIO CONTENT — edit everything on the site from this one file.
//  Every section of the page reads from `portfolioData` below.
// ============================================================================

export type SocialPlatform = 'linkedin' | 'github' | 'phone'

export interface Social {
  platform: SocialPlatform
  href: string
}

export interface Badge {
  text: string
  /** green = active/new, yellow = milestone (e.g. Acquired), gray = neutral */
  color: 'green' | 'yellow' | 'gray'
}

export interface LinkItem {
  label: string
  /** External URL or a file in /public (e.g. '/docs/poster.pdf'). */
  href: string
}

export interface ExperienceItem {
  /** Image path (e.g. '/logos/workiva.png'), single letter, or emoji. */
  logo: string
  company: string
  role: string
  dates?: string
  badge?: Badge
  /** Small links shown next to the company name (e.g. a poster). */
  links?: LinkItem[]
}

export interface ProjectItem {
  /** Emoji shown in the small rounded square. */
  logo: string
  title: string
  description: string
  /** Makes the whole row a link. Use either `href` or `links`, not both. */
  href?: string
  /** Small links shown next to the title (e.g. a report and its model). */
  links?: LinkItem[]
  badge?: Badge
}

export interface ThoughtItem {
  title: string
  date?: string
  href?: string
}

export interface MiscItem {
  title: string
  description?: string
  links?: LinkItem[]
}

export interface PortfolioData {
  name: string
  /** Square photo in /public (e.g. '/headshot.jpg'), shown as a circle next to the name. */
  headshot?: string
  tagline: string
  email: string
  socials: Social[]
  experience: ExperienceItem[]
  projects: ProjectItem[]
  economicsProjects: ProjectItem[]
  education: ExperienceItem[]
  thoughts: ThoughtItem[]
  /** Shown under Thoughts when the list above is empty. */
  thoughtsPlaceholder: string
  misc: MiscItem[]
}

export const portfolioData: PortfolioData = {
  name: 'Satvik Talchuru',
  headshot: '/headshot.jpg',
  tagline: 'Software engineer with experience in pre-sales and cloud.',
  email: 'satvik.talchuru@gmail.com',

  socials: [
    { platform: 'linkedin', href: 'https://www.linkedin.com/in/satviktalchuru/' },
    { platform: 'github', href: 'https://github.com/satviktalchuru' },
    { platform: 'phone', href: 'tel:9259185702' },
  ],

  experience: [
    {
      logo: '/logos/workiva.png',
      company: 'Workiva',
      role: 'Software Engineer Intern, Infrastructure',
      dates: 'Sep 2026 – Dec 2026',
      badge: { text: 'Current', color: 'green' },
    },
    {
      logo: '/logos/workiva.png',
      company: 'Workiva',
      role: 'Software Engineer Intern, Platform',
      dates: 'Jun 2026 – Sep 2026',
    },
    {
      logo: '/logos/siemens.png',
      company: 'Siemens',
      role: 'AI Solutions Engineer Intern',
      dates: 'Jun 2025 – Dec 2025',
    },
    {
      logo: '/logos/ucsb.png',
      company: 'UCSB Information Technology',
      role: 'Cloud Solutions Architect Intern',
      dates: 'Mar 2025 – Mar 2026',
      links: [{ label: 'Poster', href: '/docs/ucsb-cloud-solutions-architect-poster.pdf' }],
    },
    {
      logo: '/logos/ucsb.png',
      company: 'UCSB Information Technology',
      role: 'ServiceNow Developer',
      dates: 'Aug 2024 – Dec 2026',
    },
  ],

  projects: [
    {
      logo: '🎯',
      title: 'earnedcommitment',
      description: 'iOS app that holds you to your goals',
      href: 'https://github.com/satviktalchuru/earned-commitment',
    },
    {
      logo: '☕',
      title: 'brew',
      description: 'Coffee ranking iOS app with ELO taste profiles',
      href: 'https://github.com/satviktalchuru/brew',
    },
    {
      logo: '👁️',
      title: 'perceptionops',
      description: 'Release gates that decide when AV perception models ship',
      href: 'https://github.com/satviktalchuru/perceptionops',
    },
    {
      logo: '📜',
      title: 'certflow.ai',
      description: 'TLS certificate reliability & ownership platform for SRE teams',
      href: 'https://github.com/satviktalchuru/certflow-ai',
    },
    {
      logo: '📊',
      title: 'maturitykit',
      description: 'Digital maturity assessments with roadmaps generated by LLMs',
      href: 'https://github.com/satviktalchuru/maturity-kit',
    },
  ],

  economicsProjects: [
    {
      logo: '📈',
      title: 'Salesforce DCF valuation',
      description: 'DCF and reverse DCF valuation of Salesforce (CRM)',
      links: [
        { label: 'Report', href: '/docs/salesforce-dcf-valuation.pdf' },
        { label: 'Model', href: '/docs/salesforce-reverse-dcf.xlsx' },
      ],
    },
    {
      logo: '📝',
      title: 'Building Without a Paycheck',
      description: "Personnel economics study of UCSB's founder residency",
      links: [{ label: 'Paper', href: '/docs/econ-187-building-without-a-paycheck.pdf' }],
    },
  ],

  education: [
    {
      logo: '/logos/ucsb.png',
      company: 'UC Santa Barbara',
      role: 'Statistics & Data Science + Economics',
      dates: 'Sep 2023 – Dec 2026',
    },
  ],

  thoughts: [],
  thoughtsPlaceholder: 'More to come.',

  misc: [{ title: '📚 🏍️ 📸 🏃' }],
}
